---
- name: Create BigchainDB environment
  shell: |
    sudo -i -u {{ bigchaindb_user }} bash <<EOF
    # create a virtualenv
    python -m venv --clear ~/env/bigchaindb
    EOF
  become: yes

- name: Apply v2.0.0b9 fixes
  # Explicitly install wheel (v2.0.0b9 install fix).
  shell: |
    sudo -i -u {{ bigchaindb_user }} bash <<EOF
    source ~/env/bigchaindb/bin/activate
    pip install wheel
    deactivate
    EOF
  become: yes
  when: bigchaindb_version == "v2.0.0b9"

- name: Install Bigchaindb
  shell: |
    sudo -i -u {{ bigchaindb_user }} bash <<EOF
    source ~/env/bigchaindb/bin/activate
    # install
    pip install -U bigchaindb=={{ bigchaindb_version }}
    deactivate
    EOF
  become: yes

- name: Apply v2.0.0b9 fixes step 2.
  # Install tendermint abci
  # NOTE: I don't know why but it works when bigchaindb is already installed.
  # It probably has something to do with protobufs.
  shell: |
    sudo -i -u {{ bigchaindb_user }} bash <<EOF
    source ~/env/bigchaindb/bin/activate
    pip install tm-abci
    deactivate
    EOF
  become: yes
  when: bigchaindb_version == "v2.0.0b9"

- name: Bigchaindb configuration
  shell: |
    sudo -i -u {{ bigchaindb_user }} bash <<EOF
    source ~/env/bigchaindb/bin/activate

    bigchaindb -y configure

    # expose to the internet
    sed -i 's/"bind": "localhost:9984"/"bind": "0.0.0.0:9984"/' ~/.bigchaindb

    # logging config
    sed -i 's@"file": "/home/{{ bigchaindb_user }}/bigchaindb\.log"\
    @"file": "{{ bigchaindb_log_folder }}/bigchaindb/bigchaindb.log"@' ~/.bigchaindb

    sed -i 's@"error_file": "/home/{{ bigchaindb_user }}/bigchaindb-errors.log"\
    @"error_file": "{{ bigchaindb_log_folder }}/bigchaindb/bigchaindb-errors.log"@' ~/.bigchaindb

    deactivate
    EOF
  become: yes

- name: Configure log folder
  shell: |
    mkdir {{ bigchaindb_log_folder }}/bigchaindb
    chown {{ bigchaindb_user }}:{{ bigchaindb_group }} {{ bigchaindb_log_folder }}/bigchaindb
  become: yes

- name: Place systemd unit file
  template:
    src: service.j2
    dest: /lib/systemd/system/bigchaindb.service
    owner: root
    group: root
  become: yes
